alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
name: st-template-daemon
region: sfo
services:
- dockerfile_path: Dockerfile
  envs:
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: ""
  git:
    branch: main
    repo_clone_url: https://github.com/Stactica/st-template-daemon.git
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: st-template-daemon
  routes:
  - path: /
  source_dir: /

